// This array represents the optimal quest order for an efficient Ironman.
export const ironmanQuestOrder: string[] = [
	// First Steps
	"Cook's Assistant",
	"The Restless Ghost",
	"Sheep Shearer",
	"Witch's Potion",
	"Diamond in the Rough",
	"Stolen Hearts",
	"What's Mine is Yours",
	"Rune Mysteries",
	"Buyers and Cellars",
	"Gunnar's Ground",
	"A Shadow over Ashdale",

	// Early Game
	"Wolf Whistle",
	"Druidic Ritual",
	"Priest in Peril",
	"Animal Magnetism",
	"Waterfall Quest",
	"Missing, Presumed Death",
	"Let Them Eat Pie",
	"The Blood Pact",
	"Vampyre Slayer",
	"Death Plateau",
	"The Golem",
	"Shadow of the Storm",
	"A Tail of Two Cats",
	"The Lost Tribe",
	"Death to the Dorgeshuun",
	"The Dig Site",
	"One Piercing Note",
	"Song from the Depths",
	"Myths of the White Lands",
	"Observatory Quest",
	"Hazeel's Cult",
	"Plague City",
	"Biohazard",
	"Murder Mystery",
	"Recruitment Drive",
	"Black Knights' Fortress",
	"The Holy Grail",
	"Merlin's Crystal",
	"Jungle Potion",
	"Shilo Village",
	"One Small Favour",
	"Tribal Totem",
	"Creature of Fenkenstrain",
	"The Grand Tree",
	"Tree Gnome Village",
	"Monkey Madness I",
	"Horror from the Deep",
	"Witch's House",
	"Haunted Mine",
	"Lair of Tarn Razorlor",
	"Ghosts Ahoy",
	"Dragon Slayer I",

	// Mid Game
	"The Eyes of Glouphrie",
	"The Prisoner of Glouphrie",
	"Making History",
	"Mountain Daughter",
	"In Aid of the Myreque",
	"In Search of the Myreque",
	"Darkness of Hallowvale",
	"Legacy of Seergaze",
	"The Branches of Darkmeyer",
	"Desert Treasure",
	"The Temple at Senntisten",
	"Fairy Tale I - Growing Pains",
	"Fairy Tale II - Cure a Queen",
	"Fairy Tale III - Battle at Ork's Rift",
	"The Fremennik Trials",
	"The Fremennik Isles",
	"Glorious Memories",
	"Lunar Diplomacy",
	"Dream Mentor",
	"King's Ransom",
	"Underground Pass",
	"Regicide",
	"Roving Elves",
	"Mourning's End Part I",
	"Mourning's End Part II",
	"Within the Light",
	"Plague's End",
	"The Light Within",
	"Children of Mah",

	// Late Game
	"The World Wakes",
	"The Firemaker's Curse",
	"Ritual of the Mahjarrat",
	"The Mighty Fall",
	"The Void Stares Back",
	"A Void Dance",
	"Sliske's Endgame",

	// End Game
	"Curse of the Black Stone",
	"Impressing the Locals",
	"Desperate Times",
	"Desperate Measures",
	"City of Senntisten",
	"Extinction",
	"Twilight of the Gods",
	"Aftermath",
	"Daughter of Chaos",
	"Succession",
	"Unwelcome Guests",
	"Eye of Het I",
	"Eye of Het II",
	"Civil War I",
	"Civil War II",
	"Civil War III",
	"Ancient Awakening",
	"Necromancy!",
	"Vessel of the Harbinger",
	"That Old Black Magic",
	"Kili Row",
	"Alpha vs Omega",
	"Tome of Um",
	"Memory of a Master",
	"Spirit of War",
	"A New Beginning",
	"Rune Mythos",
	"Eclipse of the Heart",
];
