export type TimelineTier = {
	name: string;
	quests: string[];
};

export const TIMELINE_TIERS: TimelineTier[] = [
	{
		name: "Pathfinder",
		quests: [
			"Cook's Assistant",
			"The Blood Pact",
			"The Restless Ghost",
			"Demon Slayer",
			"Shield of Arrav",
			"Rune Mysteries",
			"Rune Memories",
			"Imp Catcher",
			"Stolen Hearts",
			"Diamond in the Rough",
			"Ernest the Chicken",
			"Vampyre Slayer",
			"Goblin Diplomacy",
			"Pirate's Treasure",
			"Druidic Ritual",
			"Monk's Friend",
			"Clock Tower",
			"Hazeel Cult",
			"Sheep Herder",
			"Plague City",
			"Observatory Quest",
			"Dwarf Cannon",
			"Murder Mystery",
			"Gertrude's Cat",
			"Priest in Peril",
			"Death Plateau",
			"A Soul's Bane",
			"Rag and Bone Man",
			"Wolf Whistle",
			"Swept Away",
			"Myths of the White Lands",
			"One Piercing Note",
			"Let Them Eat Pie",
			"Song from the Depths",
			"A Shadow over Ashdale",
			"Broken Home",
			"Violet is Blue",
			"Once Upon a Slime",
			"Duck Quest",
		],
	},
	{
		name: "Adventurer",
		quests: [
			"What's Mine is Yours",
			"Fishing Contest",
			"Biohazard",
			"Jungle Potion",
			"Elemental Workshop I",
			"Nature Spirit",
			"Recruitment Drive",
			"Eagles' Peak",
			"Tower of Life",
			"Perils of Ice Mountain",
			"The Tale of the Muspah",
			"Fur 'n Seek",
			"Rune Mechanics",
			"Buyers and Cellars",
			"Gunnar's Ground",
			"Bringing Home the Bacon",
			"The Jack of Spades",
			"Chef's Assistant",
			"Violet is Blue Too",
		],
	},
	{
		name: "Champion",
		quests: [
			"Dragon Slayer",
			"The Knight's Sword",
			"Lost City",
			"Witch's House",
			"Merlin's Crystal",
			"Scorpion Catcher",
			"Tribal Totem",
			"Holy Grail",
			"Tree Gnome Village",
			"Sea Slug",
			"Waterfall Quest",
			"The Tourist Trap",
			"Watchtower",
			"The Dig Site",
			"Big Chompy Bird Hunting",
			"Tai Bwo Wannai Trio",
			"Shades of Mort'ton",
			"The Fremennik Trials",
			"In Search of the Myreque",
			"Creature of Fenkenstrain",
			"Ghosts Ahoy",
			"Mountain Daughter",
			"The Feud",
			"The Golem",
			"Icthlarin's Little Helper",
			"Tears of Guthix",
			"Zogre Flesh Eaters",
			"The Lost Tribe",
			"The Giant Dwarf",
			"Forgettable Tale of a Drunken Dwarf",
			"Garden of Tranquillity",
			"A Tail of Two Cats",
			"Wanted!",
			"Shadow of the Storm",
			"Making History",
			"Rat Catchers",
			"Spirits of the Elid",
			"The Hand in the Sand",
			"In Aid of the Myreque",
			"Death to the Dorgeshuun",
			"The Darkness of Hallowvale",
			"The Slug Menace",
			"Elemental Workshop II",
			"Enlightened Journey",
			"Animal Magnetism",
			"Cold War",
			"What Lies Below",
			"Olaf's Quest",
			"Another Slice of H.A.M.",
			"Kennith's Concerns",
			"Smoking Kills",
			"Spirit of Summer",
			"Meeting History",
			"All Fired Up",
			"Missing My Mummy",
			"Hunt for Red Raktuber",
			"Elemental Workshop III",
			"Quiet Before the Swarm",
			"Elemental Workshop IV",
			"Salt in the Wound",
			"Carnillean Rising",
			"Beneath Cursed Tides",
			"You Are It",
		],
	},
	{
		name: "Heroic",
		quests: [
			"Heroes' Quest",
			"Troll Stronghold",
			"Eadgar's Ruse",
			"My Arm's Big Adventure",
			"The Grand Tree",
			"The Eyes of Glouphrie",
			"Family Crest",
			"Temple of Ikov",
			"Fight Arena",
			"Shilo Village",
			"Underground Pass",
			"Horror from the Deep",
			"Throne of Miscellania",
			"Haunted Mine",
			"Troll Romance",
			"One Small Favour",
			"Between a Rock...",
			"Rum Deal",
			"Devious Minds",
			"Enakhra's Lament",
			"Cabin Fever",
			"A Fairy Tale I - Growing Pains",
			"Royal Trouble",
			"A Fairy Tale II - Cure a Queen",
			"Lunar Diplomacy",
			"The Fremennik Isles",
			"King's Ransom",
			"The Path of Glouphrie",
			"Land of the Goblins",
			"As a First Resort",
			"Legacy of Seergaze",
			"TokTz-Ket-Dill",
			"Summer's End",
			"Defender of Varrock",
			"In Pyre Need",
			"The Chosen Commander",
			"A Fairy Tale III - Battle at Ork's Rift",
			"A Void Dance",
			"Some Like It Cold",
		],
	},
	{
		name: "Legendary",
		quests: [
			"Legends' Quest",
			"Monkey Madness",
			"Desert Treasure",
			"Regicide",
			"Roving Elves",
			"Mourning's End Part I",
			"Mourning's End Part II",
			"Recipe for Disaster",
			"Swan Song",
			"Contact!",
			"The Great Brain Robbery",
			"Dream Mentor",
			"Grim Tales",
			"Back to my Roots",
			"Dealing with Scabaras",
			"Catapult Construction",
			"Rocking Out",
			"Glorious Memories",
			"The Curse of Arrav",
			"Forgiveness of a Chaos Dwarf",
			"Within the Light",
			"The Temple at Senntisten",
			"Blood Runs Deep",
			"Love Story",
			"Do No Evil",
			"King of the Dwarves",
			"The Prisoner of Glouphrie",
			"A Clockwork Syringe",
			"Deadliest Catch",
			"The Branches of Darkmeyer",
			"The Firemaker's Curse",
			"The Elder Kiln",
			"The Lord of Vampyrium",
			"Crocodile Tears",
			"Our Man in the North",
			"'Phite Club",
		],
	},
	{
		name: "Mythic",
		quests: [
			"While Guthix Sleeps",
			"Nomad's Requiem",
			"The Void Stares Back",
			"Ritual of the Mahjarrat",
			"The Brink of Extinction",
			"Birthright of the Dwarves",
			"Plague's End",
			"River of Blood",
			"Pieces of Hate",
		],
	},
	{
		name: "World Guardian",
		quests: [
			"The World Wakes",
			"Sins of the Father",
			"The Death of Chivalry",
			"Missing, Presumed Death",
			"One of a Kind",
			"Fate of the Gods",
			"The Mighty Fall",
			"Heart of Stone",
			"Dishonour among Thieves",
			"Dimension of Disaster",
			"Hero's Welcome",
			"The Light Within",
			"Call of the Ancestors",
			"Nomad's Elegy",
			"Kindred Spirits",
			"Gower Quest",
			"Children of Mah",
			"Impressing the Locals",
			"Sliske's Endgame",
			"Back to the Freezer",
			"Evil Dave's Big Day Out",
			"The Needle Skips",
			"Curse of the Black Stone",
			"Desperate Times",
			"Desperate Measures",
			"Desperate Creatures",
			"Raksha the Shadow Colossus",
			"The Vault of Shadows",
			"Heartstealer",
			"Azzanadra's Quest",
			"Battle of the Monolith",
			"City of Senntisten",
			"Once Upon a Time in Gielinor",
			"Eye of Het I",
			"Eye of Het II",
			"Extinction",
			"Twilight of the Gods",
			"Aftermath",
		],
	},
	{
		name: "Age of Chaos",
		quests: [
			"Daughter of Chaos",
			"Succession",
			"New Foundations",
			"Murder on the Border",
			"Unwelcome Guests",
			"Dead and Buried",
			"Necromancy!",
			"Rune Mythos",
			"Vessel of the Harbinger",
			"The Spirit of War",
			"Tomes of the Warlock",
			"Remains of the Necrolord",
			"Alpha vs Omega",
			"Kili Row",
			"That Old Black Magic",
			"Ancient Awakening",
			"Battle of Forinthry",
			"Housing of Parliament",
			"Requiem for a Dragon",
			"Osseous Rex",
			"Soul Searching",
			"Ode of the Devourer",
			"Beneath Scabaras' Sands",
			"Pharaoh's Folly",
			"Eclipse of the Heart",
			"Stellar Born",
			"Princess and the Pauper",
		],
	},
	{
		name: "Seasonal",
		quests: [
			"It's Snow Bother",
			"Great Egg-spectations",
			"Field of Screams",
			"A Christmas Reunion",
			"Guys and Dolls",
			"Cold Front",
		],
	},
];

export const timelineQuestOrder: string[] = TIMELINE_TIERS.flatMap(
	(tier) => tier.quests,
);

const tierLookup = new Map<string, string>();
for (const tier of TIMELINE_TIERS) {
	for (const quest of tier.quests) {
		tierLookup.set(quest, tier.name);
	}
}

export function getTimelineTier(questName: string): string | undefined {
	return tierLookup.get(questName);
}
